#!/bin/bash
ls -al
pwd
echo "Running the packer script now..!!"
echo .
echo .
#packer build packer.json
packer build -var 'aws_access_key=AKIAYG2VVLDJN76VR3OK' -var 'aws_secret_key=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' packer.json
echo .
echo .
terraform init
terraform apply --var-file test.tfvars -var 'aws_access_key=AKIAYG2VVLDJN76VR3OK' -var 'aws_secret_key=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' -auto-approve
echo "Infra Built Sucessfully....!!!"
#docker -H 10.1.1.111 run --rm -dit --name nginx1 --hostname nginx1 -p 8000:80 nginx:latest
